// <auto-generated />
using System;
using BTCPayServer.Plugins.Boltz.Arkade.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BTCPayServer.Plugins.Boltz.Arkade.Data.Migrations
{
    [DbContext(typeof(ArkPluginDbContext))]
    partial class ArkPluginDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("BTCPayServer.Plugins.Boltz.Arkade")
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BTCPayServer.Plugins.Boltz.Arkade.Data.NativeKeyIndexEntity", b =>
                {
                    b.Property<string>("WalletId")
                        .HasColumnType("text");

                    b.Property<long>("NextIndex")
                        .HasColumnType("bigint");

                    b.HasKey("WalletId");

                    b.ToTable("NativeKeyIndices", "BTCPayServer.Plugins.Boltz.Arkade");
                });

            modelBuilder.Entity("BTCPayServer.Plugins.Boltz.Arkade.Data.NativeSwapEntity", b =>
                {
                    b.Property<string>("WalletId")
                        .HasColumnType("text");

                    b.Property<string>("SwapId")
                        .HasColumnType("text");

                    b.Property<bool>("IsTerminal")
                        .HasColumnType("boolean");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("WalletId", "SwapId");

                    b.HasIndex("WalletId", "IsTerminal");

                    b.ToTable("NativeSwaps", "BTCPayServer.Plugins.Boltz.Arkade");
                });

            modelBuilder.Entity("BTCPayServer.Plugins.Boltz.Arkade.Data.UsdSettlementTransferEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ArbitrumClaimTxHash")
                        .HasColumnType("text");

                    b.Property<string>("ArkFundingTxId")
                        .HasColumnType("text");

                    b.Property<long?>("ArkLegFeeSats")
                        .HasColumnType("bigint");

                    b.Property<string>("BridgeKind")
                        .HasColumnType("text");

                    b.Property<string>("BridgeRef")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("DeliveredOutputAtomic")
                        .HasColumnType("bigint");

                    b.Property<string>("DestinationAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DestinationAsset")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DestinationNetwork")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<long>("ExpectedOutputAtomic")
                        .HasColumnType("bigint");

                    b.Property<string>("Invoice")
                        .HasColumnType("text");

                    b.Property<long>("InvoiceAmountSats")
                        .HasColumnType("bigint");

                    b.Property<string>("NnarkSwapId")
                        .HasColumnType("text");

                    b.Property<string>("PaymentHash")
                        .HasColumnType("text");

                    b.Property<string>("RustSwapId")
                        .HasColumnType("text");

                    b.Property<long>("SourceAmountSats")
                        .HasColumnType("bigint");

                    b.Property<long?>("StableLegFeeSats")
                        .HasColumnType("bigint");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StoreId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TbtcLockupTxId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WalletId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("NnarkSwapId")
                        .IsUnique()
                        .HasFilter("\"NnarkSwapId\" IS NOT NULL");

                    b.HasIndex("RustSwapId")
                        .IsUnique()
                        .HasFilter("\"RustSwapId\" IS NOT NULL");

                    b.HasIndex("WalletId", "State");

                    b.ToTable("UsdSettlementTransfers", "BTCPayServer.Plugins.Boltz.Arkade");
                });

            modelBuilder.Entity("NArk.Storage.EfCore.Entities.ArkIntentEntity", b =>
                {
                    b.Property<string>("IntentTxId")
                        .HasColumnType("text");

                    b.Property<string>("BatchId")
                        .HasColumnType("text");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("text");

                    b.Property<string>("CommitmentTransactionId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeleteProof")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeleteProofMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IntentId")
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("PartialForfeits")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("RegisterProof")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RegisterProofMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SignerDescriptor")
                        .HasColumnType("text");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ValidUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WalletId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IntentTxId");

                    b.HasIndex("IntentId")
                        .IsUnique()
                        .HasFilter("\"IntentId\" IS NOT NULL");

                    b.ToTable("Intents", "BTCPayServer.Plugins.Boltz.Arkade");
                });

            modelBuilder.Entity("NArk.Storage.EfCore.Entities.ArkIntentVtxoEntity", b =>
                {
                    b.Property<string>("IntentTxId")
                        .HasColumnType("text");

                    b.Property<string>("VtxoTransactionId")
                        .HasColumnType("text");

                    b.Property<int>("VtxoTransactionOutputIndex")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LinkedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IntentTxId", "VtxoTransactionId", "VtxoTransactionOutputIndex");

                    b.HasIndex("VtxoTransactionId", "VtxoTransactionOutputIndex");

                    b.ToTable("IntentVtxos", "BTCPayServer.Plugins.Boltz.Arkade");
                });

            modelBuilder.Entity("NArk.Storage.EfCore.Entities.ArkSwapEntity", b =>
                {
                    b.Property<string>("SwapId")
                        .HasColumnType("text");

                    b.Property<string>("WalletId")
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("ContractScript")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ExpectedAmount")
                        .HasColumnType("bigint");

                    b.Property<string>("FailReason")
                        .HasColumnType("text");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Invoice")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("Metadata");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("SwapType")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SwapId", "WalletId");

                    b.HasIndex("WalletId");

                    b.HasIndex("ContractScript", "WalletId");

                    b.ToTable("Swaps", "BTCPayServer.Plugins.Boltz.Arkade");
                });

            modelBuilder.Entity("NArk.Storage.EfCore.Entities.ArkWalletContractEntity", b =>
                {
                    b.Property<string>("Script")
                        .HasColumnType("text");

                    b.Property<string>("WalletId")
                        .HasColumnType("text");

                    b.Property<int>("ActivityState")
                        .HasColumnType("integer");

                    b.Property<string>("ContractDataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("ContractData");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("Metadata");

                    b.Property<int>("Scope")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Script", "WalletId");

                    b.HasIndex("ActivityState");

                    b.HasIndex("Scope");

                    b.HasIndex("WalletId");

                    b.ToTable("WalletContracts", "BTCPayServer.Plugins.Boltz.Arkade");
                });

            modelBuilder.Entity("NArk.Storage.EfCore.Entities.ArkWalletEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AccountDescriptor")
                        .HasColumnType("text");

                    b.Property<int>("LastUsedIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Metadata")
                        .HasColumnType("text");

                    b.Property<string>("Wallet")
                        .HasColumnType("text");

                    b.Property<string>("WalletDestination")
                        .HasColumnType("text");

                    b.Property<int>("WalletType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("Wallet")
                        .IsUnique()
                        .HasFilter("\"Wallet\" IS NOT NULL");

                    b.ToTable("Wallets", "BTCPayServer.Plugins.Boltz.Arkade");
                });

            modelBuilder.Entity("NArk.Storage.EfCore.Entities.VtxoEntity", b =>
                {
                    b.Property<string>("TransactionId")
                        .HasColumnType("text");

                    b.Property<int>("TransactionOutputIndex")
                        .HasColumnType("integer");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<string>("ArkTxid")
                        .HasColumnType("text");

                    b.Property<string>("AssetsJson")
                        .HasColumnType("text");

                    b.Property<string>("CommitmentTxids")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("ExpiresAtHeight")
                        .HasColumnType("bigint");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("Metadata");

                    b.Property<bool>("Preconfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("Recoverable")
                        .HasColumnType("boolean");

                    b.Property<string>("Script")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("SeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SettledByTransactionId")
                        .HasColumnType("text");

                    b.Property<string>("SpentByTransactionId")
                        .HasColumnType("text");

                    b.Property<bool>("Unrolled")
                        .HasColumnType("boolean");

                    b.HasKey("TransactionId", "TransactionOutputIndex");

                    b.ToTable("Vtxos", "BTCPayServer.Plugins.Boltz.Arkade");
                });

            modelBuilder.Entity("NArk.Storage.EfCore.Entities.ArkIntentVtxoEntity", b =>
                {
                    b.HasOne("NArk.Storage.EfCore.Entities.ArkIntentEntity", "Intent")
                        .WithMany("IntentVtxos")
                        .HasForeignKey("IntentTxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NArk.Storage.EfCore.Entities.VtxoEntity", "Vtxo")
                        .WithMany("IntentVtxos")
                        .HasForeignKey("VtxoTransactionId", "VtxoTransactionOutputIndex")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Intent");

                    b.Navigation("Vtxo");
                });

            modelBuilder.Entity("NArk.Storage.EfCore.Entities.ArkSwapEntity", b =>
                {
                    b.HasOne("NArk.Storage.EfCore.Entities.ArkWalletEntity", "Wallet")
                        .WithMany("Swaps")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NArk.Storage.EfCore.Entities.ArkWalletContractEntity", "Contract")
                        .WithMany("Swaps")
                        .HasForeignKey("ContractScript", "WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("NArk.Storage.EfCore.Entities.ArkWalletContractEntity", b =>
                {
                    b.HasOne("NArk.Storage.EfCore.Entities.ArkWalletEntity", "Wallet")
                        .WithMany("Contracts")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("NArk.Storage.EfCore.Entities.ArkIntentEntity", b =>
                {
                    b.Navigation("IntentVtxos");
                });

            modelBuilder.Entity("NArk.Storage.EfCore.Entities.ArkWalletContractEntity", b =>
                {
                    b.Navigation("Swaps");
                });

            modelBuilder.Entity("NArk.Storage.EfCore.Entities.ArkWalletEntity", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("Swaps");
                });

            modelBuilder.Entity("NArk.Storage.EfCore.Entities.VtxoEntity", b =>
                {
                    b.Navigation("IntentVtxos");
                });
#pragma warning restore 612, 618
        }
    }
}
